### ISSUE TITLE
Build warning crashes deploy

### ISSUE THREAD

**Issue by mousse-tache** [msieurmoustache/gaabp#13]
see https://github.com/webpack-contrib/mini-css-extract-plugin/issues/250#issuecomment-415345126

**Comment by steveswork** [comment]
There is now an NPM package named  **[@webkrafters/ordercss](https://www.npmjs.com/package/@webkrafters/ordercss)** which tackles this issue.

Full disclosure: I initially created it to solve this very problem in one of my apps but decided to expand it and share it with everyone.

If this package helps anyone, please share it with others.

Thanks and good luck!
