### ISSUE TITLE
Problèmes

### ISSUE THREAD

**Issue by Madlidou** [msieurmoustache/gaabp#32]
Texte Qui nous sommes : 

- 5 buts mais 4 énoncés

S’inscrire : 
-	Mettre lien vers la liste de nos groupes (genre maps avec des points pour nos groupes
S’impliquer : 
-	Pour ce faire, il y aura vérification des antécédents judiciaires de l'intéressé qu'il ne présente pas de risque
-	L'intéressé devra également être en contact avec le groupe dans lequel il désire s'impliquer et ses membres pourront le guider le processus.

Devise des louveteaux
Branche rouge : syntaxe

**Comment by msieurmoustache** [comment]
Pour la liste des groupes, ce sera traité [ici](https://github.com/msieurmoustache/gaabp/issues/33)
J'ai corrigé le reste, dont un seul truc au niveau de la branche rouge, as-tu plus de détails ou même une suggestion de modification?
