### ISSUE TITLE
Tutoriel pour ajouter un membre.

### ISSUE THREAD

**Issue by Madlidou** [msieurmoustache/gaabp#34]
Comment ajouter un membre à mon unité? 

 Si le membre n’existe pas dans la base de données : 

1-	Aller dans l’onglet Membres du site web. 
2-	Cliquer sur le + et entrer les informations du membre (adresse courriel et nom complet) puis cliquer sur Ajouter.
3-	Suivre les indications pour ajouter un membre ci-dessous. 

Si le membre existe déjà dans la base de données :
1-	Aller sur la page de l’unité où le membre doit être ajouté en cliquant sur le lien sous l’onglet Mes unités à gauche de la page. 
2-	Descendre sur la page et cliquer sur Recenser des membres dans l’unité. 
3-	Chercher le membre par son nom, tel qu’entré dans la base de données.
4-	Définir le rôle du membre pour ajuster la cotisation. Elle se met à jour automatiquement.
5-	Cliquer sur Ajouter à l’unité.

***Sur Word, j'ai mis les ''noms'' des trucs sur quoi il faut cliquer en italique avec une majuscule.

**Comment by msieurmoustache** [comment]
Voir wiki
