### ISSUE TITLE
Impossible de compléter l'inscription

### ISSUE THREAD

**Issue by malandles** [msieurmoustache/gaabp#60]
**Describe the bug**
Après s'être connecté, tous les pages me redirige vers la page de profil pour compléter mon inscription. Cependant, peu importe les informations entrées, un message de succès est affiché, puis je suis redirigé a nouveau vers le profil qui n'a visiblement pas été sauvegardé.

Peut-être que les données de mon compte son corrompues, voir `marcandrew.landles@4elegardeur.org`.

Il semble ne pas y avoir de validation non plus. Si je n'inscris pas mon nom/prénom:
```
undefined undefined, votre inscription a été complétée
```

**To Reproduce**
1. Connexion
2. Ajouté de l'information dans le profil
3. Appuyer sur "COMPLÉTER L'INSCRIPTION"
4. Voir message de succès
5. Redirection ver le profil
6. Champs sont de nouveau vides

**Expected behavior**
- Les champs devraient se sauvegarder
- Avoir une validation minimale

**Screenshots**

Avec les champs remplis:
![Screen Shot 2021-09-16 at 3 35 23 PM](https://user-images.githubusercontent.com/25748497/133675948-2d968636-87c4-4d41-9bd1-7ffdefcc45f1.png)

Avec aucun champs rempli:
![Screen Shot 2021-09-16 at 3 33 37 PM](https://user-images.githubusercontent.com/25748497/133675958-6c803b24-4df7-46f9-b71b-9b33e8151f70.png)

Après la redirection:
![Screen Shot 2021-09-16 at 3 40 56 PM](https://user-images.githubusercontent.com/25748497/133675977-dc9c3685-2f94-444d-b0a1-f28fdc2fb33c.png)

**Desktop (please complete the following information):**
 - OS: mac OS
 - Browsers: 
   - Brave v1.27.111
   - Chrome v93.0.4577.63
   - Firefox v92

**Additional context**
Je serais disponible pour faire du QA ou contribuer de temps en temps. Je suis Lead Développeur dans l'industrie du web. Je vais t'envoyer un courriel après avoir ouvert ce issue.

**Comment by msieurmoustache** [comment]
J'ai fixé le endpoint vers lequel le client pointait hier, mais j'ai pas validé que le payload correspondait à ce qui était attendu. J'ai un fix qui arrive.

**Comment by msieurmoustache** [comment]
En passant, je vais juste prendre ton email et le lier à ton dossier membre, ça va t'éviter cette étape-là.

**Comment by msieurmoustache** [comment]
Ce commit-là devrait réglé le problème https://github.com/msieurmoustache/gaabp/commit/5a8d7d21aff36f9b42f95d883cee9e4d9b7e58c7
